import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import os
import json

from models.skill_matcher import SkillMatchSiameseNet
from training.metrics import make_writer


# ---------------------------------------------------------------------------
# Contrastive Loss
# ---------------------------------------------------------------------------

class ContrastiveLoss(nn.Module):
    """
    Based on: http://yann.lecun.com/exdb/publis/pdf/hadsell-chopra-lecun-06.pdf
    label=1 → similar (match), label=0 → dissimilar (mismatch)
    """
    def __init__(self, margin=2.0):
        super().__init__()
        self.margin = margin

    def forward(self, output1, output2, label):
        dist = F.pairwise_distance(output1, output2, keepdim=True)
        loss = torch.mean(
            label * torch.pow(dist, 2) +
            (1 - label) * torch.pow(
                torch.clamp(self.margin - dist, min=0.0), 2
            )
        )
        return loss


# ---------------------------------------------------------------------------
# Real dataset — loaded from data/skill_pairs.json (generated by generate_skill_data.py)
# ---------------------------------------------------------------------------

class RealSkillDataset(Dataset):
    def __init__(self, json_path):
        with open(json_path, "r", encoding="utf-8") as f:
            self.data = json.load(f)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        return (
            item["cv_skills"],
            item["jd_requirements"],
            torch.tensor([float(item["is_match"])], dtype=torch.float32),
        )


# ---------------------------------------------------------------------------
# Fallback dummy dataset
# ---------------------------------------------------------------------------

class DummySkillDataset(Dataset):
    def __init__(self, num_samples=100):
        self.num_samples = num_samples
        self.cv_skills = [
            "Python, Django, REST APIs, PostgreSQL",
            "Java, Spring Boot, Microservices",
            "React.js, Node.js, Express, MongoDB",
            "C++, Unreal Engine, 3D Math",
        ]
        self.jd_skills = [
            "Backend Web Developer with Python frameworks",
            "Enterprise Java Engineer",
            "Fullstack JavaScript Developer (MERN)",
            "Game Developer (C++ / Blueprints)",
        ]

    def __len__(self):
        return self.num_samples

    def __getitem__(self, idx):
        is_match  = idx % 2
        base_idx  = (idx // 2) % len(self.cv_skills)
        cv_text   = self.cv_skills[base_idx]
        if is_match:
            jd_text = self.jd_skills[base_idx]
            label   = 1.0
        else:
            jd_text = self.jd_skills[(base_idx + 1) % len(self.jd_skills)]
            label   = 0.0
        return cv_text, jd_text, torch.tensor([label], dtype=torch.float32)


# ---------------------------------------------------------------------------
# Pairwise accuracy on a held-out validation set
# ---------------------------------------------------------------------------

def compute_pairwise_accuracy(model, val_loader, device):
    """
    For each (match, mismatch) pair from the same batch, check that
    the model assigns a lower distance to matches than mismatches.
    """
    model.eval()
    correct, total = 0, 0

    with torch.no_grad():
        for cv_texts, jd_texts, labels in val_loader:
            labels = labels.to(device)
            cv_vecs, jd_vecs = model(list(cv_texts), list(jd_texts))
            dists = F.pairwise_distance(cv_vecs, jd_vecs)

            # Compare every pair (i, j) where label[i]=1 and label[j]=0
            for i in range(len(labels)):
                for j in range(len(labels)):
                    if labels[i].item() == 1.0 and labels[j].item() == 0.0:
                        total += 1
                        if dists[i].item() < dists[j].item():
                            correct += 1

    return correct / total if total > 0 else 0.0


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"Starting Siamese Network training on {device}...")

    # Choose dataset — prefer real data if available
    json_path = "data/skill_pairs.json"
    if os.path.exists(json_path):
        full_dataset = RealSkillDataset(json_path)
        print(f"Loaded {len(full_dataset)} real skill pairs from {json_path}")
        checkpoint_name = "skill_matcher_v2.pt"
    else:
        print(
            "WARNING: data/skill_pairs.json not found. "
            "Run training/generate_skill_data.py first for real data. "
            "Falling back to DummySkillDataset."
        )
        full_dataset    = DummySkillDataset(num_samples=160)
        checkpoint_name = "skill_matcher_v1.pt"

    # 80/20 train/val split
    train_size  = int(0.8 * len(full_dataset))
    val_size    = len(full_dataset) - train_size
    train_dataset, val_dataset = torch.utils.data.random_split(
        full_dataset, [train_size, val_size]
    )

    train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
    val_loader   = DataLoader(val_dataset,   batch_size=16)

    model     = SkillMatchSiameseNet().to(device)
    criterion = ContrastiveLoss(margin=2.0)
    optimizer = optim.AdamW(model.shared_mlp.parameters(), lr=1e-3)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="min", patience=2, factor=0.5)
    writer    = make_writer("skill_matcher")

    epochs           = 10
    best_loss        = float("inf")
    patience         = 4
    patience_counter = 0

    for epoch in range(epochs):
        model.train()
        total_loss = 0.0

        for cv_texts, jd_texts, labels in train_loader:
            labels = labels.to(device)
            optimizer.zero_grad()
            cv_vectors, jd_vectors = model(list(cv_texts), list(jd_texts))
            loss = criterion(cv_vectors, jd_vectors, labels)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()

        avg_loss     = total_loss / len(train_loader)
        pairwise_acc = compute_pairwise_accuracy(model, val_loader, device)

        scheduler.step(avg_loss)

        writer.add_scalar("Loss/train",              avg_loss,     epoch)
        writer.add_scalar("Metric/pairwise_accuracy", pairwise_acc, epoch)

        print(
            f"Epoch {epoch+1}/{epochs} | "
            f"Contrastive Loss: {avg_loss:.4f} | "
            f"Pairwise Accuracy: {pairwise_acc:.4f}"
        )

        if avg_loss < best_loss:
            best_loss        = avg_loss
            patience_counter = 0
            os.makedirs("models/checkpoints", exist_ok=True)
            torch.save(
                model.state_dict(),
                f"models/checkpoints/{checkpoint_name}"
            )
            print(f"  --> Checkpoint saved: {checkpoint_name}")
        else:
            patience_counter += 1
            if patience_counter >= patience:
                print(f"Early stopping at epoch {epoch+1} (best loss: {best_loss:.4f})")
                break

    writer.close()
    print("\nTraining Complete!")

    # Inference test
    print("\n--- Quick Inference Test ---")
    model.eval()
    test_cv        = "I have 3 years of experience building web apps with Django and Python."
    test_jd_match  = "Looking for a Python backend engineer."
    test_jd_mismatch = "Looking for a React frontend developer."

    match_score    = model.calculate_match_score(test_cv, test_jd_match)
    mismatch_score = model.calculate_match_score(test_cv, test_jd_mismatch)

    print(f"Match Score    (should be HIGH): {match_score:.4f}")
    print(f"Mismatch Score (should be LOW):  {mismatch_score:.4f}")


if __name__ == "__main__":
    main()
